package main

import (
	"bytes"
	"crypto/sha256"
	"encoding"
	"fmt"
	"log"
)

func main() {
	const (
		example1 = "this is a example "
		example2 = "second example"
	)
	firstHash := sha256.New()
	firstHash.Write([]byte(example1))
	marshaler, ok := firstHash.(encoding.BinaryMarshaler)
	if !ok {
		log.Fatal("first Hash is not generated by encoding.BinaryMarshaler")
	}
	data, err := marshaler.MarshalBinary()
	if err != nil {
		log.Fatal("failure to create first Hash:", err)
	}
	secondHash := sha256.New()
	unmarshaler := secondHash.(encoding.BinaryUnmarshaler)
	if !ok {
		log.Fatal("second Hash is not generated by encoding.BinaryUnmarshaler")
	}
	if err := unmarshaler.UnmarshalBinary(data); err != nil {
		log.Fatal("failure to create hash:", err)
	}
	firstHash.Write([]byte(example2))
	secondHash.Write([]byte(example2))
	fmt.Printf("%x\n", firstHash.Sum(nil))
	fmt.Println(bytes.Equal(firstHash.Sum(nil), secondHash.Sum(nil)))
}
